### ISSUE TITLE
Question on migrator agnostic

### ISSUE THREAD

**Issue by toymachiner62** [wzrdtales/node-ultimate-migrate#11]
I see in your README that you have this as a goal:

> Completely independent from the Migrator used (X Language)
> I want to be able to use a different Migrator (for example Laravel Migrations).

Can you elaborate on how you expect this to work? From my understanding does this mean you want to be able to use Laravel's' migration command (PHP) to run a migration that was generated in Node.js with node-ultimate-migrate library?

This seems like way overkill to me..

**Comment by wzrdtales** [comment]
The scope of umigrate is basically a reverse generator, but it's wrapping also db-migrate and providing thus migration capabilities itself.

Also I'm now a collaborator on db-migrate and going to improve this.

The support of indpendencne of the migrator is done by a simple template driver. At least the data that gets collected is always the same and only the syntax and code structure is some kind of different.

**Comment by wzrdtales** [comment]
To add: This feature is set to near to the final version, thus the really important things are done first.

**Comment by wzrdtales** [comment]
Also to note, db-migrate will keep the migrator and umigrate will be a reverse migrator itself directly bound to db-migrate.
So everything migration related will be done within db-migrate.

**Comment by wzrdtales** [comment]
To specify this a bit more, the goal I set with this is. Umigrate might be used to generate the migrations out of your existing schema, while still sticking to your original migrator.

**Comment by toymachiner62** [comment]
I think i understand. So if i just need mongodb support for Node.js I should probably update db-migrate and submit a pull request for that and umigrate would just wrap that functionality?

**Comment by wzrdtales** [comment]
Exactly!

**Comment by wzrdtales** [comment]
The main reason I don't write the reverse generator as standalone is, that from my point of view it makes more sense to have a migration solution that covers both. So no one needs to switch always from the one to the other one. But the same time I want to provide the freedom to do so.

So to all things migration related and schema reversing, your pull request or issue is within db-migrate absolutely suitable.

If you've any further question, don't hesitate and just ask :)

**Comment by wzrdtales** [comment]
I think the question should be answered, feel free to reopen again if this isn' the case.
